# Generated by Django 3.2.5 on 2021-07-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Specialization', models.CharField(max_length=200)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='doctors')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=190, unique=True)),
                ('Address', models.CharField(max_length=300)),
                ('Status', models.IntegerField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='shops')),
                ('opening_hours', models.CharField(max_length=100)),
            ],
        ),
    ]
