# Generated by Django 3.2.5 on 2022-11-20 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOrdered', models.DateField(auto_now=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('paymentDone', models.BooleanField(default=False)),
                ('transactionId', models.CharField(blank=True, max_length=12, null=True)),
                ('total_price', models.FloatField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pathological_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestName', models.CharField(max_length=100)),
                ('Desc', models.TextField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='shops')),
                ('SampleType', models.CharField(max_length=100)),
                ('FastingRequirement', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='Clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='store.shop'),
        ),
        migrations.AlterField(
            model_name='service',
            name='Doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='store.doctor'),
        ),
        migrations.AlterField(
            model_name='servicedetailsday',
            name='Day',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicedetailsday',
            name='ServiceID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviceDetailsDays', to='store.service'),
        ),
        migrations.AlterField(
            model_name='servicedetailsdaytime',
            name='ServiceDetailsDayID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviceDetailsDayTimes', to='store.servicedetailsday'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='OffDay',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], default='7', max_length=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='Shop_owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FlatName', models.CharField(max_length=200)),
                ('StreetName', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=10)),
                ('AddressType', models.CharField(max_length=200)),
                ('MobileNumber', models.CharField(max_length=15)),
                ('AppointmentDate', models.DateField()),
                ('AppointmentTimeSlot', models.TimeField()),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shippingAddress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phlebotomist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Phlebotomists', to='store.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Pathological_Test_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.IntegerField()),
                ('ReportDeliveryTime', models.TimeField()),
                ('Shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PathologicalTestServices', to='store.shop')),
                ('Tests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PathologicalTestServices', to='store.pathological_test')),
            ],
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateAdded', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('0', 'Not assigned'), ('1', 'Assigned'), ('2', 'delivered'), ('3', 'Not Delivered'), ('4', 'Collected'), ('5', 'Not Collected')], default='0', max_length=1)),
                ('collected_date', models.DateField(null=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='reports')),
                ('Cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderServices', to='store.cart')),
                ('Order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderServices', to='store.order')),
                ('PathologicalTestService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderServices', to='store.pathological_test_service')),
            ],
        ),
    ]
