# Generated by Django 3.2.5 on 2022-01-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220104_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='OffDay',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], default='7', max_length=10),
        ),
    ]
