# Generated by Django 3.2.5 on 2022-01-17 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_alter_shop_offday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOrdered', models.DateField()),
                ('complete', models.BooleanField(default=False)),
                ('transactionId', models.CharField(max_length=12)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pathological_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestName', models.CharField(max_length=100)),
                ('Desc', models.TextField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='shops')),
                ('SampleType', models.CharField(max_length=100)),
                ('FastingRequirement', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='servicedetailsday',
            name='ServiceID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviceDetailsDays', to='store.service'),
        ),
        migrations.AlterField(
            model_name='servicedetailsdaytime',
            name='ServiceDetailsDayID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviceDetailsDayTimes', to='store.servicedetailsday'),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=5)),
                ('FlatName', models.CharField(max_length=200)),
                ('StreetName', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=10)),
                ('AddressType', models.CharField(max_length=200)),
                ('MobileNumber', models.CharField(max_length=15)),
                ('AppointmentDate', models.DateField()),
                ('AppointmentTimeSlot', models.TimeField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippingAddresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phlebotomist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Phlebotomists', to='store.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Pathological_Test_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.IntegerField()),
                ('ReportDeliveryTime', models.TimeField()),
                ('Shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PathologicalTestServices', to='store.shop')),
                ('Tests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PathologicalTestServices', to='store.pathological_test')),
            ],
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateAdded', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderServices', to='store.order')),
                ('PathologicalTestService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathologicalTestServices', to='store.pathological_test_service')),
            ],
        ),
    ]
