# Generated by Django 3.2.5 on 2021-07-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210715_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetails',
            name='day',
            field=models.CharField(choices=[('S', 'SUNDAY'), ('M', 'MONDAY'), ('T', 'TUESDAY'), ('W', 'WEDNESDAY'), ('TH', 'THURSDAY'), ('F', 'FRIDAY'), ('ST', 'SATURDAY')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicedetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
