# Generated by Django 3.2.5 on 2022-01-26 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='PathologicalTestService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderServices', to='store.pathological_test_service'),
        ),
    ]
