# Generated by Django 3.2.5 on 2021-09-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210806_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Experience',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
