# Generated by Django 3.2.5 on 2021-09-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_doctor_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='Integer_image',
            field=models.ImageField(blank=True, null=True, upload_to='shops'),
        ),
    ]
