# Generated by Django 3.2.5 on 2022-02-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20220202_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentDone',
            field=models.BooleanField(default=False),
        ),
    ]
