# Generated by Django 3.2.5 on 2021-09-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_shop_offday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='offDay',
            field=models.CharField(choices=[('6', 'Sunday'), ('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday')], default=1, max_length=5),
        ),
    ]
