# Generated by Django 3.2.5 on 2021-09-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_shop_offday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetails',
            name='Fees',
        ),
        migrations.AddField(
            model_name='service',
            name='Fees',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
