# Generated by Django 3.2.5 on 2022-03-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_shop_shop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='collected_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports'),
        ),
        migrations.AddField(
            model_name='orderservice',
            name='status',
            field=models.CharField(choices=[('0', 'Not assigned'), ('1', 'Assigned'), ('2', 'delivered'), ('3', 'Not Delivered'), ('4', 'Collected'), ('5', 'Not Collected')], default='0', max_length=1),
        ),
    ]
