# Generated by Django 3.2.5 on 2021-09-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210917_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='day',
            field=models.CharField(choices=[('6', 'Sunday'), ('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday')], max_length=2, null=True),
        ),
    ]
