# Generated by Django 3.2.5 on 2021-10-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_service_day'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('Clinic', 'day', 'Doctor')},
        ),
    ]
