# Generated by Django 3.2.5 on 2021-10-13 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_service_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicedetails',
            unique_together={('ServiceID', 'Time')},
        ),
    ]
