# Generated by Django 3.2.5 on 2021-10-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_shop_shop_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Experience',
            field=models.IntegerField(),
        ),
    ]
