# Generated by Django 3.2.5 on 2023-06-21 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(max_length=200, verbose_name='patient_name')),
                ('Age', models.IntegerField(verbose_name='age')),
                ('Sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, verbose_name='gender')),
                ('phone', models.CharField(max_length=10)),
                ('Status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('cancelled', 'cancelled')], default='pending', max_length=10, verbose_name='status')),
                ('Rank', models.IntegerField(blank=True, default=0, null=True)),
                ('slot_date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.servicedetailsdaytime', verbose_name='service')),
                ('appointment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_appointment', to=settings.AUTH_USER_MODEL, verbose_name='who create the appointment')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
