# Generated by Django 3.2.5 on 2021-12-19 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(max_length=200, verbose_name='patient_name')),
                ('Age', models.IntegerField(verbose_name='age')),
                ('Sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, verbose_name='gender')),
                ('phone', models.CharField(max_length=10)),
                ('Status', models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Accepted'), ('C', 'Cancelled')], max_length=10, null=True, verbose_name='status')),
                ('Rank', models.IntegerField(default=0, verbose_name='rank')),
                ('day', models.CharField(max_length=50)),
                ('time', models.CharField(default='Noon', max_length=10)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('Service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.servicedetailsdaytime', verbose_name='service')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
