# Generated by Django 3.2.5 on 2021-07-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Age',
            field=models.IntegerField(verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Rank',
            field=models.IntegerField(verbose_name='rank'),
        ),
    ]
