# Generated by Django 3.2.5 on 2021-07-11 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_service_servicedetails'),
        ('customer', '0002_auto_20210711_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.service', verbose_name='service'),
        ),
    ]
