# Generated by Django 3.2.5 on 2022-03-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20220328_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.CharField(default='M', max_length=50),
            preserve_default=False,
        ),
    ]
