# Generated by Django 3.2.5 on 2021-07-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_appointment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Rank',
            field=models.IntegerField(default=0, verbose_name='rank'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Status',
            field=models.CharField(blank=True, choices=[('D', 'Done'), ('A', 'Absent'), ('M-S', 'Meeting-Start')], max_length=10, null=True, verbose_name='status'),
        ),
    ]
