# Generated by Django 3.2.5 on 2023-05-16 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0004_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='who_create',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='create_appointment_user', to='auth_app.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_appointment', to=settings.AUTH_USER_MODEL, verbose_name='customer'),
        ),
    ]
