# Generated by Django 3.2.5 on 2023-05-19 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0006_remove_appointment_who_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='shop_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shop_owner_appointment', to='auth_app.user', verbose_name='shop owner'),
            preserve_default=False,
        ),
    ]
