# Generated by Django 3.2.5 on 2023-05-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_appointment_shop_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='shop_owner',
            new_name='shop_owner_appointment',
        ),
    ]
