# Generated by Django 3.2.5 on 2023-05-19 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_rename_shop_owner_appointment_shop_owner_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='shop_owner_appointment',
            new_name='shop_owner',
        ),
    ]
