# Generated by Django 3.2.5 on 2021-08-11 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210806_2236'),
        ('customer', '0009_auto_20210811_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='ServiceDetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.servicedetails', verbose_name='service'),
        ),
    ]
