# Generated by Django 3.2.5 on 2021-08-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20210811_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='ServiceDetail',
            new_name='Service',
        ),
    ]
