# Generated by Django 3.2.5 on 2021-08-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20210810_0004'),
        ('customer', '0011_rename_servicedetail_appointment_service'),
    ]

    operations = [
    ]
