# Generated by Django 3.2.5 on 2021-09-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_rename_servicedetail_appointment_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default='9876543210', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
