# Generated by Django 3.2.5 on 2021-09-11 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_shop_offday'),
        ('customer', '0012_appointment_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.service', verbose_name='service'),
        ),
    ]
