# Generated by Django 3.2.5 on 2021-09-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_merge_20210919_2037'),
        ('customer', '0016_alter_appointment_date'),
    ]

    operations = [
    ]
