# Generated by Django 2.1.9 on 2021-07-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='no_subscription_popup',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscribe',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='angular_project_subscription',
            field=models.BooleanField(default=False, help_text='Check this field to remove Angular Tutorial popup blocker for this user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='angular_tutorial_subscription',
            field=models.BooleanField(default=False, help_text='Check this field to remove Angular Tutorial popup blocker for this user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='django_project_subscription',
            field=models.BooleanField(default=False, help_text='Check this field to remove Angular Tutorial popup blocker for this user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='django_tutorial_subscription',
            field=models.BooleanField(default=False, help_text='Check this field to remove Django Tutorial popup blocker for this user'),
        ),
    ]
