# Generated by Django 2.1.9 on 2022-05-05 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_api', '0002_auto_20210716_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='angular_project_subscription',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='angular_tutorial_subscription',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='app_source',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='django_project_subscription',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='django_tutorial_subscription',
        ),
    ]
