# Generated by Django 3.2.5 on 2022-02-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='flat_name',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='is_EmailVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_PhoneVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='landmark',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(default=4353),
        ),
    ]
