# Generated by Django 3.2.5 on 2022-11-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='is_EmailVerified',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='flat_name',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='is_PhoneVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='landmark',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(default=2037),
        ),
    ]
