# Generated by Django 3.2.5 on 2021-07-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('cr', 'customer'), ('so', 'shopowner')], default='customer', max_length=20, null=True),
        ),
    ]
