# Generated by Django 3.2.5 on 2023-05-13 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_alter_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
