# Generated by Django 3.2.5 on 2023-05-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0017_remove_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('cr', 'customer'), ('so', 'shopowner')], default='customer', max_length=20),
        ),
    ]
