# Generated by Django 3.2.5 on 2022-04-12 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0016_auto_20220305_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestNameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PathologicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pathological_test_images')),
                ('description', models.TextField(blank=True, null=True)),
                ('sample_type', models.CharField(blank=True, max_length=55, null=True)),
                ('precautions', models.CharField(blank=True, max_length=255, null=True)),
                ('fees', models.PositiveSmallIntegerField()),
                ('delivery_duration', models.CharField(blank=True, max_length=25, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_name', to='store.shop')),
                ('test_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_name', to='pathological_test.testnametype')),
            ],
        ),
    ]
