# Generated by Django 3.2.5 on 2022-04-25 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20220305_0033'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pathological_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_for', models.CharField(max_length=35)),
                ('pickup_date', models.DateField()),
                ('pickup_from', models.TextField()),
                ('zipcode', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('0', 'Not assigned'), ('1', 'Assigned'), ('2', 'delivered'), ('3', 'Not Delivered'), ('4', 'Collected'), ('5', 'Not Collected')], default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PathologicalTestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pathological_test_images')),
                ('fees', models.PositiveSmallIntegerField()),
                ('delivery_duration', models.CharField(blank=True, max_length=25, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_name', to='store.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateField(auto_now=True)),
                ('complete', models.BooleanField(default=False)),
                ('payment_done', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=12, null=True)),
                ('total_price', models.FloatField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='pathologicaltest',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='pathologicaltest',
            name='delivery_duration',
        ),
        migrations.RemoveField(
            model_name='pathologicaltest',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='pathologicaltest',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pathologicaltest',
            name='test_name',
        ),
        migrations.AddField(
            model_name='pathologicaltest',
            name='name',
            field=models.CharField(default='Blood', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TestNameType',
        ),
        migrations.AddField(
            model_name='shopingcart',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='pathological_test.pathologicaltest'),
        ),
        migrations.AddField(
            model_name='shopingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pathologicaltestdetail',
            name='test_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_name', to='pathological_test.pathologicaltest'),
        ),
        migrations.AddField(
            model_name='orderaddresh',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to='pathological_test.userorder'),
        ),
    ]
