# Generated by Django 3.2.5 on 2022-05-01 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20220305_0033'),
        ('pathological_test', '0002_auto_20220426_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phlebotomist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=135)),
                ('phone_number', models.CharField(max_length=12)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phlebotomists', to='store.shop')),
            ],
        ),
    ]
