# Generated by Django 3.2.5 on 2022-05-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathological_test', '0004_auto_20220501_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='sample_collected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
