# Generated by Django 2.1.9 on 2022-06-08 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pathological_test', '0007_auto_20220519_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=190, unique=True)),
                ('Address', models.CharField(max_length=300)),
                ('Status', models.CharField(choices=[('E', 'ENABLE'), ('D', 'DISABLE')], default='E', max_length=2)),
                ('Interior_image', models.ImageField(blank=True, null=True, upload_to='shops')),
                ('OffDay', models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], default='7', max_length=10)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='shops')),
                ('Opening_time', models.TimeField(blank=True, null=True)),
                ('Closing_time', models.TimeField(blank=True, null=True)),
                ('Shop_url', models.URLField(default='www.watduwant.com/show_details')),
                ('Shop_owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Specialization', models.CharField(max_length=200)),
                ('Experience', models.IntegerField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='doctors')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_name', to='pathological_test.Clinic')),
            ],
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_detail', to='pathological_test.Clinic'),
        ),
        migrations.AlterField(
            model_name='pathologicaltestdetail',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic', to='pathological_test.Clinic'),
        ),
        migrations.AlterField(
            model_name='phlebotomist',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phlebotomists', to='pathological_test.Clinic'),
        ),
    ]
